# Generated by Django 3.2.3 on 2021-05-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_cart_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartquantity',
            name='user',
        ),
        migrations.AddField(
            model_name='cartquantity',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.cart'),
        ),
    ]
