# Generated by Django 3.2.3 on 2021-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_cartproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartquantity',
            options={'verbose_name_plural': 'Cart Quantities'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
