# Generated by Django 3.2.3 on 2021-05-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
