# Generated by Django 3.2.3 on 2021-05-21 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
