# Generated by Django 3.2.3 on 2021-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20210521_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantities',
            field=models.ManyToManyField(related_name='quantities', to='market.CartQuantity'),
        ),
    ]
