# Generated by Django 3.2.3 on 2021-05-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20210522_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField(default=0)),
                ('end_hour', models.IntegerField(default=23)),
                ('total_people', models.IntegerField(default=0)),
                ('alloted', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.store')),
            ],
        ),
    ]
