# Generated by Django 3.2.3 on 2021-05-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(default='12345678', max_length=15),
        ),
    ]
