# Generated by Django 3.2.3 on 2021-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_alter_store_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/images/products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to='uploads/images/logos'),
        ),
    ]
