# Generated by Django 3.2.3 on 2021-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='stores',
            field=models.ManyToManyField(related_name='customers', to='market.Store'),
        ),
    ]
